name: flutter_fiveflix
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5 
  lottie: ^3.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/symbol.png
    - assets/images/gameGuessTheMovie.png
    - assets/images/profile.jpg
    - assets/images/loading.gif

  fonts:
    - family: NetflixSans
      fonts:
        - asset: assets/fonts/NetflixSans-Regular.otf
        - asset: assets/fonts/NetflixSans-Bold.otf
          weight: 700
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue-Regular.ttf
          weight: 700
